name: Test
on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  matrix-testing:
    runs-on: ubuntu-20.04

    continue-on-error: ${{ matrix.allow_failures || false }}
    env:
      RAILS_VERSION: "DEFAULT"
      OTHER: "SOMETHING"
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 2.7
            RAILS_VERSION: "5.1"
          - ruby: "3.0"
            RAILS_VERSION: "5.2"

    steps:
      - uses: actions/checkout@v2

      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby }}"
          bundler-cache: true

      - name: report back!
        run: |
          export RAILS_VERSION=${{ matrix.RAILS_VERSION }}"
          echo RAILS_VERSION "$RAILS_VERSION"
          echo OTHER "$OTHER"
          echo WHAT "$WHAT"
          ruby -v
          echo "ruby ${{ matrix.ruby }}"
          echo "OTHER e ${{ env.OTHER }}"
          echo "RAILS_VERSION e ${{ env.RAILS_VERSION }}"
